# Generated by Django 2.1.15 on 2020-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0002_auto_20200212_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yundan',
            name='YUN011',
            field=models.CharField(default='N', max_length=20),
        ),
        migrations.AlterField(
            model_name='yundan',
            name='YUN013',
            field=models.CharField(default='N', max_length=20),
        ),
    ]
