# Generated by Django 2.1.15 on 2020-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0003_auto_20200212_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='yundan',
            name='YUN015',
            field=models.CharField(default='Y', max_length=20),
        ),
    ]
