# Generated by Django 2.1.15 on 2020-02-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0005_auto_20200212_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('SKU01', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SKU02', models.CharField(max_length=40, null=True)),
                ('SKU03', models.FloatField(default=0)),
                ('SKU04', models.FloatField(default=0)),
                ('SKU05', models.CharField(default='Y', max_length=2)),
            ],
        ),
    ]
