# Generated by Django 2.1.15 on 2020-02-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0006_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='YUN_ORDER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OR001', models.CharField(max_length=20, null=True)),
                ('OR002', models.CharField(max_length=20, null=True)),
                ('OR003', models.CharField(max_length=40, null=True)),
                ('OR004', models.CharField(max_length=20, null=True)),
                ('OR005', models.IntegerField(default=0)),
                ('OR006', models.CharField(max_length=20, null=True)),
                ('OR007', models.CharField(max_length=20, null=True)),
                ('OR008', models.CharField(max_length=20, null=True)),
                ('OR009', models.CharField(max_length=20, null=True)),
                ('OR010', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
