# Generated by Django 2.1.15 on 2020-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0008_auto_20200216_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='yun_order',
            name='OR011',
            field=models.CharField(default='N', max_length=20),
        ),
        migrations.AddField(
            model_name='yun_order',
            name='OR012',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='yun_order',
            name='OR013',
            field=models.CharField(default='N', max_length=20),
        ),
        migrations.AddField(
            model_name='yun_order',
            name='OR014',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
