# Generated by Django 2.1.15 on 2020-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0009_auto_20200216_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yun_order',
            name='OR010',
            field=models.CharField(default='N', max_length=20),
        ),
    ]
