# Generated by Django 2.1.15 on 2020-02-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0011_yundan_yun016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yun_order',
            name='OR014',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
