# Generated by Django 2.1.15 on 2020-03-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0013_yundan_yun017'),
    ]

    operations = [
        migrations.AddField(
            model_name='yundan',
            name='YUN018',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
