# Generated by Django 2.1.15 on 2020-03-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0014_yundan_yun018'),
    ]

    operations = [
        migrations.CreateModel(
            name='YUN_YI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YI001', models.CharField(max_length=20, null=True)),
                ('YI002', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
