# Generated by Django 2.1.15 on 2020-03-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0015_yun_yi'),
    ]

    operations = [
        migrations.AddField(
            model_name='yundan',
            name='YUN019',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='yundan',
            name='YUN020',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
