# Generated by Django 2.1.15 on 2020-03-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0016_auto_20200315_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='yundan',
            name='YUN021',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
