# Generated by Django 2.1.15 on 2020-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0018_yun_order_or015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yundan',
            name='YUN07',
            field=models.CharField(max_length=200),
        ),
    ]
