# Generated by Django 2.1.15 on 2020-03-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0019_auto_20200318_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='yundan',
            name='YUN022',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
