# Generated by Django 2.1.15 on 2020-03-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0020_yundan_yun022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yun_order',
            name='OR002',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
