# Generated by Django 2.1.15 on 2020-03-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0021_auto_20200324_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yun_order',
            name='OR008',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='yun_order',
            name='OR009',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
