# Generated by Django 2.1.15 on 2020-03-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0024_auto_20200328_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='yundan',
            name='YUN023',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
