# Generated by Django 2.1.15 on 2020-02-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0002_auto_20200212_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yundan',
            name='YUN09',
        ),
    ]
