# Generated by Django 2.1.15 on 2020-02-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0003_remove_yundan_yun09'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saomiao',
            name='TA005',
        ),
    ]
