# Generated by Django 2.1.15 on 2020-02-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cysystem', '0004_remove_saomiao_ta005'),
    ]

    operations = [
        migrations.AddField(
            model_name='yundan',
            name='YUN011',
            field=models.CharField(default='N', max_length=20),
        ),
        migrations.AddField(
            model_name='yundan',
            name='YUN012',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='yundan',
            name='YUN013',
            field=models.CharField(default='N', max_length=20),
        ),
        migrations.AddField(
            model_name='yundan',
            name='YUN014',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
